spring:
  application:
    name: ui-server
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ui-client
            scope:
              - openid
              - profile
              - email
              - Products.Read
              - Products.Write
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/skeld
            user-name-attribute: preferred_username

server:
  port: 8080

api:
  server:
    base-url: http://localhost:5001

logging:
  level:
    com.github.fresel.skeld.ui.server.config.ServiceLayerConfig: DEBUG
