issuer: http://dex:5556/dex
storage:
  type: memory
web:
  http: 0.0.0.0:5556
staticClients:
  - id: keycloak-client
    redirectURIs:
      - "http://localhost:8180/realms/skeld/broker/dex/endpoint"
      - "http://keycloak:8180/realms/skeld/broker/dex/endpoint"
    name: "Keycloak Client"
    secret: changeme
enablePasswordDB: true
staticPasswords:
  - email: "user.dev@example.com"
    hash: "$2b$12$IWs9xrMSOCni13P2ku3hleIZkJeD5EO39AEN3ACDh96/XiwlCQNRi"
    username: "user"
    userID: "11111111-1111-1111-1111-111111111111"
